/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;
//import com.sun.org.apache.xerces.internal.impl.dv.xs.DateDV;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.Driver;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
//import sun.util.calendar.BaseCalendar;
import java.util.Calendar;
import java.util.Date;

/**
 *
 * @author Rahmat Nur Hidayat_180101167_SI18A1_FIKOM_UDB
 */
public class fkembali extends javax.swing.JFrame {
private Connection con;
private Statement st;
private ResultSet RsKembali;
private ResultSet RsRental;
private ResultSet RsMobil;
private ResultSet RsStatus;
private ResultSet RsPenyewa;
private ResultSet RsM;
private String sql="";

private String tglsewa, tglbali, idkembali, idrental, idpenyewa, namapenyewa, idmobil, namamobil, status;
private int harga, lama, total;
    /**
     * Creates new form fkembali
     */
    public fkembali() {
        initComponents();
        KoneksiRental(); 
        TampilData(sql);
    }
    
    private void bersih(){
        edkembali.setText("");
        edrental.setText("");
        edpenyewa.setText("");
        edmobil.setText("");
        ednamamobil.setText("");
        ednamapenyewa.setText("");
        edharga.setText("");
        edlama.setText("");
        edtotal.setText("");
        edstatus.setText("");
        edharga.setText("");
    }
    
    private void KoneksiRental(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/rentalmobil","root","");
            System.out.println("Koneksi Berhasil");
            //JOptionPane.showMessageDialog(null, "TRANSAKSI SEWA MOBIL");
        } catch (Exception e) {
            System.out.println("Koneksi Gagal \n"+e);
        }
    }
    
    private void TampilData (String sql){
        DefaultTableModel datalist = new DefaultTableModel();
        datalist.addColumn("No");
        datalist.addColumn("ID Pengembalian");
        datalist.addColumn("ID Transaksi");
        datalist.addColumn("ID Penyewa");
        datalist.addColumn("ID Mobil");
        datalist.addColumn("Tanggal Sewa");
        datalist.addColumn("Tanggal Kembali");
        datalist.addColumn("Lama Sewa");
        datalist.addColumn("Total Bayar");
        datalist.addColumn("Status");
        try {
            int i = 1;
            st=con.createStatement();
            RsRental=st.executeQuery("select * from tb_pengembalian");
            while (RsRental.next())
                datalist.addRow(new Object[]{
                    (""+i++),
                    RsRental.getString("id_pengembalian"), RsRental.getString("id_transaksi"),
                    RsRental.getString("id_penyewa"), RsRental.getString("id_mobil"),
                    RsRental.getString("tgl_rental"), RsRental.getString("tgl_kembali"),
                    RsRental.getString("lama"), RsRental.getString("total_bayar"),
                    RsRental.getString("status")
                });
           tbkembali.setModel(datalist);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal Tampil \n"+e.getMessage());
        }
    }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        edkembali = new javax.swing.JTextField();
        edrental = new javax.swing.JTextField();
        edpenyewa = new javax.swing.JTextField();
        ednamapenyewa = new javax.swing.JTextField();
        edmobil = new javax.swing.JTextField();
        ednamamobil = new javax.swing.JTextField();
        edharga = new javax.swing.JTextField();
        edlama = new javax.swing.JTextField();
        edtotal = new javax.swing.JTextField();
        edstatus = new javax.swing.JTextField();
        tglrental = new com.toedter.calendar.JDateChooser();
        tglkembali = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbkembali = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 255, 204));

        jLabel1.setFont(new java.awt.Font("Eurostar Black Extended", 0, 24)); // NOI18N
        jLabel1.setText("TRANSAKSI PENGEMBALIAN");

        jLabel2.setText("ID Pengembalian");

        jLabel3.setText("Cari ID Transaksi");

        jLabel4.setText("ID Penyewa");

        jLabel5.setText("Nama Penyewa");

        jLabel6.setText("ID Mobil");

        jLabel7.setText("Nama Mobil");

        jLabel8.setText("Harga Sewa");

        jLabel9.setText("Tangga Rental");

        jLabel10.setText("Tanggal Kembali");

        jLabel11.setText("Lama / Hari");

        jLabel12.setText("Total Bayar");

        edkembali.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                edkembaliKeyPressed(evt);
            }
        });

        edrental.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                edrentalKeyPressed(evt);
            }
        });

        edpenyewa.setEnabled(false);

        ednamapenyewa.setEnabled(false);

        edmobil.setEnabled(false);

        ednamamobil.setEnabled(false);

        edharga.setEnabled(false);

        edlama.setEnabled(false);

        edtotal.setEnabled(false);

        edstatus.setEnabled(false);

        tglrental.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tglrentalPropertyChange(evt);
            }
        });

        tglkembali.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tglkembaliPropertyChange(evt);
            }
        });

        jLabel14.setText("Status");

        tbkembali.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbkembali);

        jButton1.setText("SIMPAN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("HAPUS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("BATAL");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("KELUAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(edkembali)
                                    .addComponent(edrental)
                                    .addComponent(edpenyewa)
                                    .addComponent(ednamapenyewa)
                                    .addComponent(edmobil)
                                    .addComponent(ednamamobil, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel14))
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(edtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(edlama, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tglkembali, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tglrental, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(edharga, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(edstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4)
                                .addGap(0, 404, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 684, Short.MAX_VALUE)
                                .addContainerGap())))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(edkembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton2)
                        .addComponent(jButton4)
                        .addComponent(jButton3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(edrental, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(edpenyewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(ednamapenyewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(edmobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(ednamamobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(edharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(tglrental, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tglkembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(edlama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(edtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(edstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tglrentalPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tglrentalPropertyChange
        // TODO add your handling code here:
            if(tglrental.getDate()!=null){
            SimpleDateFormat format=new SimpleDateFormat("yyyy-MM-dd");
            tglsewa=format.format(tglrental.getDate());
        }
    }//GEN-LAST:event_tglrentalPropertyChange

    private void tglkembaliPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tglkembaliPropertyChange
        // TODO add your handling code here:
        if(tglkembali.getDate()!=null){
            SimpleDateFormat format=new SimpleDateFormat("yyyy-MM-dd");
            tglbali=format.format(tglkembali.getDate());
        }
        try {
            DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
            Date pinjam = tglrental.getDate();
            Date kembali = tglkembali.getDate();
            long pinjam1 = pinjam.getTime();
            long kembali1 = kembali.getTime();
            long diff = kembali1-pinjam1;
            long lamasewa = diff/(24*60*60*1000);
            edlama.setText(Long.toString(lamasewa));
            harga = Integer.parseInt(edharga.getText());
            lama = Integer.parseInt(edlama.getText());
            total = harga*lama;
            edtotal.setText(String.valueOf(total));
        } catch (Exception e) {
        }
    }//GEN-LAST:event_tglkembaliPropertyChange

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        fmenu m=new fmenu();
        m.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void edkembaliKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edkembaliKeyPressed
        // TODO add your handling code here:
        idkembali=edkembali.getText();
        int tekanenter=evt.getKeyCode();
        if (tekanenter==10){
            try {
                sql="select * from tb_pengembalian where id_pengembalian='"+ idkembali +"'";
                st=con.createStatement();
                RsKembali=st.executeQuery(sql);
                while (RsKembali.next()){
                    edrental.setText(RsKembali.getString("id_transaksi"));
                    edpenyewa.setText(RsKembali.getString("id_penyewa"));
                    ednamapenyewa.setText(RsKembali.getString("nama_penyewa"));
                    edmobil.setText(RsKembali.getString("id_mobil"));
                    ednamamobil.setText(RsKembali.getString("nama_mobil"));
                    edharga.setText(RsKembali.getString("harga_rental"));
                    tglrental.setDate(RsKembali.getDate("tgl_rental"));
                    tglkembali.setDate(RsKembali.getDate("tgl_kembali"));
                    edlama.setText(RsKembali.getString("Lama"));
                    edtotal.setText(RsKembali.getString("total_bayar"));
                    edstatus.setText(RsKembali.getString("status"));
                   JOptionPane.showMessageDialog(null, "Data Ditemukan !");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Data Tydak Ditemukan ! "+e.getMessage());
                edkembali.requestFocus();
            }
        }
    }//GEN-LAST:event_edkembaliKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (edkembali.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Cari Data Yang Ingin Dihapus !");
            }
        else{
        try {
            sql="DELETE FROM tb_pengembalian"
                    +" where id_pengembalian='"+ idkembali +"'";
            st=con.createStatement();
            st.execute(sql);
            bersih();
            TampilData(sql);
            JOptionPane.showMessageDialog(null, "Data Terhapus !");
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Data Tydak Terhapus ! \n"+e.getMessage());
        }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        bersih();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void edrentalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edrentalKeyPressed
        // TODO add your handling code here:
        idrental=edrental.getText();
        int tekanenter=evt.getKeyCode();
        if (tekanenter==10){
            try {
                sql="select * from tb_rental where id_transaksi='"+ idrental +"'";
                st=con.createStatement();
                RsRental=st.executeQuery(sql);
                while (RsRental.next()){
                    edpenyewa.setText(RsRental.getString("id_penyewa"));
                    ednamapenyewa.setText(RsRental.getString("nama_penyewa"));
                    edmobil.setText(RsRental.getString("id_mobil"));
                    ednamamobil.setText(RsRental.getString("nama_mobil"));
                    edharga.setText(RsRental.getString("harga_rental"));
                    tglrental.setDate(RsRental.getDate("tgl_rental"));
                    edstatus.setText(RsRental.getString("status"));
                   JOptionPane.showMessageDialog(null, "Data Ditemukan !");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog
                (null, "Data Tydak Ditemukan !"+e.getMessage());
                //edtotal.requestFocus();
            }
        }
    }//GEN-LAST:event_edrentalKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (edkembali.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Data Masih Kosong !");
        }
        else{
        idkembali=String.valueOf(edkembali.getText());
        idrental=String.valueOf(edrental.getText());
        idpenyewa=String.valueOf(edpenyewa.getText());
        namapenyewa=String.valueOf(ednamapenyewa.getText());
        idmobil=String.valueOf(edmobil.getText());
        namamobil=String.valueOf(ednamamobil.getText());
        harga=Integer.parseInt(edharga.getText());
        lama=Integer.parseInt(edlama.getText());
        total=Integer.parseInt(edtotal.getText());
        //status=String.valueOf(edstatus.getText());
         if (edstatus.getText().equals("Selesai")){
            JOptionPane.showMessageDialog(null, "Mobil Sudah Ready,\nKembali Ke Transaksi Penyewaan");
        }
        else {
        try {
            status = "Selesai";
            sql="INSERT INTO tb_pengembalian(id_pengembalian, id_transaksi, id_penyewa,"
                    + "nama_penyewa, id_mobil, nama_mobil, tgl_rental, tgl_kembali,"
                    + "lama, harga_rental, total_bayar, status)VALUE"
                    + "('"+idkembali+"','"+idrental+"','"+idpenyewa+"','"+namapenyewa+"',"
                    + "'"+idmobil+"','"+namamobil+"','"+tglsewa+"','"+tglbali+"','"+lama+"','"+harga+"',"
                    + "'"+total+"','"+status+"')";
            st=con.createStatement();
            st.execute(sql);
            bersih();
            TampilData(sql);
            JOptionPane.showMessageDialog(null, "Data Tersimpan !");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data Tydak Tersimpan !\n"+e.getMessage());
        }
             
        try {
            status="Ready";
            sql="update tb_mobil set status = '"+ status +"' where id_mobil = '"+idmobil+"'";
            st=con.createStatement();
            st.execute(sql);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Maaf Error"+e.getMessage());
        }

        try {
            status="Selesai";
            sql="update tb_rental set status = '"+ status +"' where id_transaksi = '"+idrental+"'";
            st=con.createStatement();
            st.execute(sql);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Maaf Error"+e.getMessage());
        }        
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fkembali.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fkembali.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fkembali.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fkembali.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fkembali().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField edharga;
    private javax.swing.JTextField edkembali;
    private javax.swing.JTextField edlama;
    private javax.swing.JTextField edmobil;
    private javax.swing.JTextField ednamamobil;
    private javax.swing.JTextField ednamapenyewa;
    private javax.swing.JTextField edpenyewa;
    private javax.swing.JTextField edrental;
    private javax.swing.JTextField edstatus;
    private javax.swing.JTextField edtotal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbkembali;
    private com.toedter.calendar.JDateChooser tglkembali;
    private com.toedter.calendar.JDateChooser tglrental;
    // End of variables declaration//GEN-END:variables
}
