/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.Driver;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
//import sun.util.calendar.BaseCalendar;
/**
 *
 * @author Rahmat Nur Hidayat_180101167_SI18A1_FIKOM_UDB
 */
public class frental extends javax.swing.JFrame {
private Connection con;
private Statement st;
private ResultSet RsRental;
private ResultSet RsMobil;
private ResultSet RsPenyewa;
private String sql="";

private String tanggal, transaksi, idmobil, idpenyewa, namapenyewa, namamobil, noplat, status, statusm;
private int harga;

    /**
     * Creates new form frental
     */
    public frental() {
        initComponents();
        KoneksiRental();
        TampilData(sql);
    }
    
    private void KoneksiRental(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/rentalmobil","root","");
            System.out.println("Koneksi Berhasil");
            //JOptionPane.showMessageDialog(null, "TRANSAKSI RENTAL MOBIL");
        } catch (Exception e) {
            System.out.println("Koneksi Gagal \n"+e);
        }
    }
    
    private void TampilData (String sql){
        DefaultTableModel datalist = new DefaultTableModel();
        datalist.addColumn("No");
        datalist.addColumn("ID Transaksi");
        datalist.addColumn("ID Penyewa");
        datalist.addColumn("ID Mobil");
        datalist.addColumn("Tanggal Sewa");
        datalist.addColumn("Harga Sewa");
        datalist.addColumn("Status");
        try {
            int i = 1;
            st=con.createStatement();
            RsRental=st.executeQuery("select * from tb_rental");
            while (RsRental.next())
                datalist.addRow(new Object[]{
                    (""+i++),
                    RsRental.getString(1), RsRental.getString(2),
                    RsRental.getString(3), RsRental.getString(6),
                    RsRental.getString(7), RsRental.getString(8)
                });
           tbrental.setModel(datalist);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal Tampil \n"+e.getMessage());
        }
    }
        
    private void bersih (){
        edtransaksi.setText("");
        caripenyewa.setText("");
        carimobil.setText("");
        //cbpenyewa.setSelectedItem("Pilih");
        edpenyewa.setText("");
        //cbmobil.setSelectedItem("Pilih");
        edmobil.setText("");
        edplat.setText("");
        edharga.setText("");
        edstatus.setText("");   
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        edtransaksi = new javax.swing.JTextField();
        edpenyewa = new javax.swing.JTextField();
        edmobil = new javax.swing.JTextField();
        edplat = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        edharga = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tglrental = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        edstatus = new javax.swing.JTextField();
        btsimpan = new javax.swing.JButton();
        btbatal = new javax.swing.JButton();
        btkeluar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbrental = new javax.swing.JTable();
        caripenyewa = new javax.swing.JTextField();
        carimobil = new javax.swing.JTextField();
        btdelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 255, 204));

        jLabel1.setFont(new java.awt.Font("Eurostar Black Extended", 0, 24)); // NOI18N
        jLabel1.setText("TRANSAKSI PEMINJAMAN");

        jLabel2.setText("ID Transaksi");

        jLabel3.setText("Cari ID Penyewa");

        jLabel4.setText("Cari ID Mobil");

        edtransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtransaksiActionPerformed(evt);
            }
        });
        edtransaksi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                edtransaksiKeyPressed(evt);
            }
        });

        edpenyewa.setEnabled(false);

        edmobil.setEnabled(false);

        edplat.setEnabled(false);

        jLabel5.setText("No Plat");

        jLabel6.setText("Harga Sewa");

        edharga.setEnabled(false);

        jLabel7.setText("Tanggal");

        tglrental.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tglrentalPropertyChange(evt);
            }
        });

        jLabel8.setText("Status Mobil");

        edstatus.setEnabled(false);

        btsimpan.setText("SIMPAN");
        btsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsimpanActionPerformed(evt);
            }
        });

        btbatal.setText("BATAL");
        btbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbatalActionPerformed(evt);
            }
        });

        btkeluar.setText("KELUAR");
        btkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btkeluarActionPerformed(evt);
            }
        });

        jLabel9.setText("Nama Penyewa");

        jLabel10.setText("Nama Mobil");

        tbrental.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbrental);

        caripenyewa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                caripenyewaKeyPressed(evt);
            }
        });

        carimobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carimobilActionPerformed(evt);
            }
        });
        carimobil.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                carimobilKeyPressed(evt);
            }
        });

        btdelete.setText("HAPUS");
        btdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(edharga, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel9)
                                .addComponent(jLabel10))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(edmobil, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                .addComponent(carimobil, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(edpenyewa, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(caripenyewa)
                                .addComponent(edplat)))
                        .addComponent(tglrental, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(39, 39, 39)
                            .addComponent(edtransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(edstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btsimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btbatal, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(btdelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btkeluar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(edtransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(caripenyewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edpenyewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(carimobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edmobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edplat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(edharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(tglrental, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel8))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(edstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btsimpan)
                            .addComponent(btbatal)
                            .addComponent(btkeluar)
                            .addComponent(btdelete))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsimpanActionPerformed
        // TODO add your handling code here:
        if (edtransaksi.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Data Masih Kosong !");
        }
        else{
        transaksi=String.valueOf(edtransaksi.getText());
        idpenyewa=String.valueOf(caripenyewa.getText());
        namapenyewa=String.valueOf(edpenyewa.getText());
        idmobil=String.valueOf(carimobil.getText());
        namamobil=String.valueOf(edmobil.getText());
        noplat=String.valueOf(edplat.getText());
        harga=Integer.parseInt(edharga.getText());
        //status=String.valueOf(edstatus.getText());
        if (edstatus.getText().equals("Not Ready")){
            JOptionPane.showMessageDialog(null, "Maaf Mobil Sudah Disewa !");
        }
        else{
        try {
            status = "Disewa";
            sql="INSERT INTO tb_rental(id_transaksi, id_penyewa,"
                    + "id_mobil, nama_penyewa, nama_mobil,"
                    + "harga_rental, tgl_rental, status, no_plat)VALUE"
                    + "('"+transaksi+"','"+idpenyewa+"','"+idmobil+"','"+namapenyewa+"',"
                    + "'"+namamobil+"','"+harga+"','"+tanggal+"','"+status+"','"+noplat+"')";
            st=con.createStatement();
            st.execute(sql);
            bersih();
            TampilData(sql);
            JOptionPane.showMessageDialog(null, "Data Tersimpan !");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data Tydak Tersimpan !\n"+e.getMessage());
        }
        }
        
        try {
            status="Not Ready";
            sql="update tb_mobil set status = '"+ status +"' where id_mobil = '"+idmobil+"'";
            st=con.createStatement();
            st.execute(sql);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Maaf Error"+e.getMessage());
        }
        }
    }//GEN-LAST:event_btsimpanActionPerformed

    private void btbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbatalActionPerformed
        // TODO add your handling code here:
        bersih();
    }//GEN-LAST:event_btbatalActionPerformed

    private void tglrentalPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tglrentalPropertyChange
        // TODO add your handling code here:
        if(tglrental.getDate()!=null){
            SimpleDateFormat format=new SimpleDateFormat("yyyy-MM-dd");
            tanggal=format.format(tglrental.getDate());
        }
    }//GEN-LAST:event_tglrentalPropertyChange

    private void carimobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carimobilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carimobilActionPerformed

    private void caripenyewaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caripenyewaKeyPressed
        // TODO add your handling code here:
        idpenyewa=caripenyewa.getText();
        int tekanenter=evt.getKeyCode();
        if (tekanenter==10){
            try {
                sql="select * from tb_penyewa where id_penyewa='"+ idpenyewa +"'";
                st=con.createStatement();
                RsPenyewa=st.executeQuery(sql);
                while (RsPenyewa.next()){
                    edpenyewa.setText(RsPenyewa.getString("nama_penyewa"));
                    //edalamat.setText(RsPenyewa.getString(3));
                    //edhp.setText(RsPenyewa.getString(4));
                    //edktp.setText(RsPenyewa.getString(5));
                   JOptionPane.showMessageDialog(null, "Data Ditemukan !");
                   carimobil.requestFocus();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Data Tydak Ditemukan !"+e.getMessage());
            }
        }
    }//GEN-LAST:event_caripenyewaKeyPressed

    private void carimobilKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_carimobilKeyPressed
        // TODO add your handling code here:
        idmobil=carimobil.getText();
        int tekanenter=evt.getKeyCode();
        if (tekanenter==10){
            try {
                sql="select * from tb_mobil where id_mobil='"+ idmobil +"'";
                st=con.createStatement();
                RsMobil=st.executeQuery(sql);
                while (RsMobil.next()){
                    edmobil.setText(RsMobil.getString("nama_mobil"));
                    edplat.setText(RsMobil.getString(4));
                    edharga.setText(RsMobil.getString(5));
                    edstatus.setText(RsMobil.getString(6));
                   JOptionPane.showMessageDialog(null, "Data Ditemukan !");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Data Tydak Ditemukan !"+e.getMessage());
            }
        }
    }//GEN-LAST:event_carimobilKeyPressed

    private void btkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btkeluarActionPerformed
        // TODO add your handling code here:
        fmenu m=new fmenu();
        m.setVisible(true);
        dispose();
    }//GEN-LAST:event_btkeluarActionPerformed

    private void edtransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtransaksiActionPerformed

    private void edtransaksiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtransaksiKeyPressed
        // TODO add your handling code here:
        transaksi=edtransaksi.getText();
        int tekanenter=evt.getKeyCode();
        if (tekanenter==10){
            try {
                sql="select * from tb_rental where id_transaksi='"+ transaksi +"'";
                st=con.createStatement();
                RsRental=st.executeQuery(sql);
                while (RsRental.next()){
                    caripenyewa.setText(RsRental.getString("id_penyewa"));
                    edpenyewa.setText(RsRental.getString("nama_penyewa"));
                    carimobil.setText(RsRental.getString("id_mobil"));
                    edmobil.setText(RsRental.getString("nama_mobil"));
                    edplat.setText(RsRental.getString("no_plat"));
                    edharga.setText(RsRental.getString("harga_rental"));
                    tglrental.setDate(RsRental.getDate("tgl_rental"));
                    edstatus.setText(RsRental.getString("status"));
                   JOptionPane.showMessageDialog(null, "Data Ditemukan !");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Data Tydak Ditemukan !"+e.getMessage());
                caripenyewa.requestFocus();
            }
        }
    }//GEN-LAST:event_edtransaksiKeyPressed

    private void btdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdeleteActionPerformed
        // TODO add your handling code here:
        if (edtransaksi.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Cari Data Yang Ingin Dihapus !");
            }
        else{
        try {
            sql="DELETE FROM tb_rental"
                    +" where id_transaksi='"+ transaksi +"'";
            st=con.createStatement();
            st.execute(sql);
            bersih();
            TampilData(sql);
            JOptionPane.showMessageDialog(null, "Data Terhapus !");
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Data Tydak Terhapus ! \n"+e.getMessage());
        }
        try {
            status="Ready";
            sql="update tb_mobil set status = '"+ status +"' where id_mobil = '"+idmobil+"'";
            st=con.createStatement();
            st.execute(sql);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Maaf Error"+e.getMessage());
        }
        }
    }//GEN-LAST:event_btdeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frental().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbatal;
    private javax.swing.JButton btdelete;
    private javax.swing.JButton btkeluar;
    private javax.swing.JButton btsimpan;
    private javax.swing.JTextField carimobil;
    private javax.swing.JTextField caripenyewa;
    private javax.swing.JTextField edharga;
    private javax.swing.JTextField edmobil;
    private javax.swing.JTextField edpenyewa;
    private javax.swing.JTextField edplat;
    private javax.swing.JTextField edstatus;
    private javax.swing.JTextField edtransaksi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbrental;
    private com.toedter.calendar.JDateChooser tglrental;
    // End of variables declaration//GEN-END:variables
}
